sudo: false

language: node_js

node_js:
  - "8"
  - "9"
  - "10"

notifications:
  disabled: true

install:
  - npm install -g codecov
  - npm install

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script:
  - npm test
  - codecov
